driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: amazonlinux
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
- name: default
  run_list:
  - recipe[test::single_node]
  attributes:
    graphite:
      listen_port: "8080"
      uwsgi:
        workers: 4
        listen_http: true
